#!/usr/bin/env python3
"""
Standalone Houdini .hcs theme editor with preview panels.

This tool does not ship any SideFX theme source files. Users can either:
- open their own local .hcs file
- or create a new overlay theme that references their local UIDark.hcs
"""

from __future__ import annotations

import argparse
import colorsys
import os
import re
import sys
import tkinter as tk
from dataclasses import dataclass
from pathlib import Path
from tkinter import colorchooser, filedialog, messagebox
from typing import Iterable


LINE_RE = re.compile(
    r"^(?P<indent>\s*)(?P<key>[A-Za-z0-9_]+)\s*:\s*(?P<value>.*?)(?P<comment>\s*//.*)?$"
)
DEFAULT_NEW_THEME_NAME = "CustomTheme"


def build_overlay_template_lines(scheme_name: str) -> list[str]:
    name = scheme_name.strip() or DEFAULT_NEW_THEME_NAME
    return [
        "// Generated by Houdini Theme Editor.",
        "// This file contains only user-authored overrides.",
        "// It references Houdini's local dark theme and does not bundle SideFX files.",
        '#include "$HFS/houdini/config/UIDark.hcs"',
        f"Scheme: {name}",
        "",
    ]


def clamp01(value: float) -> float:
    return max(0.0, min(1.0, value))


def rgb_to_hex(rgb: tuple[float, float, float]) -> str:
    r, g, b = (round(clamp01(channel) * 255) for channel in rgb)
    return f"#{r:02X}{g:02X}{b:02X}"


def hex_to_rgb(value: str) -> tuple[float, float, float]:
    text = value.strip().lstrip("#")
    if len(text) == 6:
        return tuple(int(text[index:index + 2], 16) / 255.0 for index in (0, 2, 4))  # type: ignore[return-value]
    raise ValueError(f"Unsupported hex color: {value}")


def format_rgb(rgb: tuple[float, float, float]) -> str:
    return " ".join(f"{clamp01(channel):.3f}".rstrip("0").rstrip(".") or "0" for channel in rgb)


def parse_float_triplet(value: str) -> tuple[float, float, float] | None:
    parts = value.strip().split()
    if len(parts) != 3:
        return None
    try:
        return tuple(clamp01(float(part)) for part in parts)  # type: ignore[return-value]
    except ValueError:
        return None


def parse_hsv(value: str) -> tuple[float, float, float] | None:
    parts = value.strip().split()
    if len(parts) != 4 or parts[0].upper() != "HSV":
        return None
    try:
        hue = float(parts[1]) / 360.0
        sat = clamp01(float(parts[2]))
        val = clamp01(float(parts[3]))
    except ValueError:
        return None
    return colorsys.hsv_to_rgb(hue, sat, val)


def parse_grey(value: str) -> tuple[float, float, float] | None:
    match = re.fullmatch(r"GREY\(([^)]+)\)", value.strip(), re.IGNORECASE)
    if not match:
        return None
    try:
        grey = clamp01(float(match.group(1)))
    except ValueError:
        return None
    return (grey, grey, grey)


def parse_hex_variants(value: str) -> tuple[float, float, float] | None:
    text = value.strip()
    if not text.startswith("#"):
        return None
    compact = text[1:].replace(" ", "")
    if len(compact) != 6:
        return None
    return hex_to_rgb("#" + compact)


def parse_named_color(value: str) -> tuple[float, float, float] | None:
    text = value.strip().upper()
    if text == "BLACK":
        return (0.0, 0.0, 0.0)
    if text == "WHITE":
        return (1.0, 1.0, 1.0)
    return None


def parse_color_value(value: str) -> tuple[float, float, float] | None:
    for parser in (parse_float_triplet, parse_hsv, parse_grey, parse_hex_variants, parse_named_color):
        parsed = parser(value)
        if parsed is not None:
            return parsed
    return None


def adjust_hsv(
    rgb: tuple[float, float, float],
    *,
    hue_shift: float = 0.0,
    sat_scale: float = 1.0,
    val_scale: float = 1.0,
    sat_offset: float = 0.0,
    val_offset: float = 0.0,
) -> tuple[float, float, float]:
    hue, sat, val = colorsys.rgb_to_hsv(*rgb)
    hue = (hue + hue_shift) % 1.0
    sat = clamp01(sat * sat_scale + sat_offset)
    val = clamp01(val * val_scale + val_offset)
    return colorsys.hsv_to_rgb(hue, sat, val)


def build_channel_family_palette(base_rgb: tuple[float, float, float]) -> list[tuple[float, float, float]]:
    return [
        adjust_hsv(base_rgb, hue_shift=-0.035, sat_scale=0.72, val_scale=1.12, val_offset=0.03),
        adjust_hsv(base_rgb, hue_shift=0.025, sat_scale=0.96, val_scale=1.10, val_offset=0.02),
        adjust_hsv(base_rgb, hue_shift=0.0, sat_scale=1.00, val_scale=1.04),
        adjust_hsv(base_rgb, hue_shift=-0.02, sat_scale=0.92, val_scale=0.92),
        adjust_hsv(base_rgb, hue_shift=0.015, sat_scale=1.04, val_scale=0.66),
    ]


def create_round_rect(canvas: tk.Canvas, x0: float, y0: float, x1: float, y1: float, radius: float, **kwargs) -> int:
    radius = max(0.0, min(radius, (x1 - x0) / 2.0, (y1 - y0) / 2.0))
    points = [
        x0 + radius, y0,
        x1 - radius, y0,
        x1, y0,
        x1, y0 + radius,
        x1, y1 - radius,
        x1, y1,
        x1 - radius, y1,
        x0 + radius, y1,
        x0, y1,
        x0, y1 - radius,
        x0, y0 + radius,
        x0, y0,
    ]
    return canvas.create_polygon(points, smooth=True, splinesteps=18, **kwargs)


@dataclass(frozen=True)
class Binding:
    section: str
    label: str
    keys: tuple[str, ...]
    fallback: tuple[float, float, float]
    note: str = ""

    @property
    def primary_key(self) -> str:
        return self.keys[0]


@dataclass
class HCSDocument:
    path: Path
    lines: list[str]

    @classmethod
    def load(cls, path: str | Path) -> "HCSDocument":
        target = Path(path)
        return cls(target, target.read_text(encoding="utf-8").splitlines())

    @classmethod
    def new_overlay(cls, scheme_name: str = DEFAULT_NEW_THEME_NAME, path: str | Path | None = None) -> "HCSDocument":
        name = scheme_name.strip() or DEFAULT_NEW_THEME_NAME
        target = Path(path) if path is not None else Path(f"{name}.hcs")
        return cls(target, build_overlay_template_lines(name))

    def __post_init__(self) -> None:
        self._reindex()

    def _reindex(self) -> None:
        self.key_to_index: dict[str, int] = {}
        self.key_to_meta: dict[str, tuple[str, str]] = {}
        self.key_to_value: dict[str, str] = {}
        for index, line in enumerate(self.lines):
            stripped = line.lstrip()
            if stripped.startswith("//") or stripped.startswith("#include"):
                continue
            match = LINE_RE.match(line)
            if not match:
                continue
            key = match.group("key")
            value = match.group("value").strip()
            comment = match.group("comment") or ""
            indent = match.group("indent") or ""
            self.key_to_index[key] = index
            self.key_to_meta[key] = (indent, comment)
            self.key_to_value[key] = value

    def get_color(self, key: str) -> tuple[float, float, float] | None:
        value = self.key_to_value.get(key)
        if value is None:
            return None
        return parse_color_value(value)

    def get_value(self, key: str) -> str | None:
        return self.key_to_value.get(key)

    def set_value(self, key: str, value: str) -> None:
        if key in self.key_to_index:
            indent, comment = self.key_to_meta.get(key, ("", ""))
            self.lines[self.key_to_index[key]] = f"{indent}{key}: {value}{comment}"
        else:
            self.lines.append(f"{key}: {value}")
        self._reindex()

    def set_color(self, key: str, rgb: tuple[float, float, float]) -> None:
        value = format_rgb(rgb)
        if key in self.key_to_index:
            indent, comment = self.key_to_meta.get(key, ("", ""))
            self.lines[self.key_to_index[key]] = f"{indent}{key}: {value}{comment}"
        else:
            self.lines.append(f"{key}: {value}")
        self._reindex()

    def save(self, path: str | Path | None = None) -> None:
        target = Path(path) if path is not None else self.path
        target.write_text(self.render_text(), encoding="utf-8")
        self.path = target

    def render_text(self) -> str:
        return "\n".join(self.lines) + "\n"

    def write_to(self, path: str | Path) -> Path:
        target = Path(path)
        target.write_text(self.render_text(), encoding="utf-8")
        return target

    def sync_scheme_name_to_path(self, path: str | Path) -> str:
        target = Path(path)
        scheme_name = target.stem.strip() or "CustomTheme"
        self.set_value("Scheme", scheme_name)
        return scheme_name


class ScrollableFrame(tk.Frame):
    def __init__(self, master: tk.Misc, bg: str) -> None:
        super().__init__(master, bg=bg)
        self.canvas = tk.Canvas(self, bg=bg, highlightthickness=0, bd=0)
        self.scrollbar = tk.Scrollbar(self, orient="vertical", command=self.canvas.yview)
        self.inner = tk.Frame(self.canvas, bg=bg)

        self.inner.bind(
            "<Configure>",
            lambda event: self.canvas.configure(scrollregion=self.canvas.bbox("all")),
        )
        self.canvas.bind(
            "<Configure>",
            lambda event: self.canvas.itemconfigure(self.window_id, width=event.width),
        )

        self.window_id = self.canvas.create_window((0, 0), window=self.inner, anchor="nw")
        self.canvas.configure(yscrollcommand=self.scrollbar.set)

        self.canvas.pack(side="left", fill="both", expand=True)
        self.scrollbar.pack(side="right", fill="y")

        self.canvas.bind_all("<MouseWheel>", self._on_mousewheel)

    def _on_mousewheel(self, event: tk.Event) -> None:
        try:
            self.canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")
        except tk.TclError:
            pass


BINDINGS: tuple[Binding, ...] = (
    Binding(
        "Parameter States",
        "Expression / keyed",
        ("IsKeyColor", "ParmFieldExpressionBG", "ParmFieldExpressionColor", "ParmFieldExprBG", "ParmExpressionBG"),
        (0.153, 0.545, 0.545),
        "Green parameter box when an expression is active on the current key.",
    ),
    Binding(
        "Parameter States",
        "Animated / not on key",
        ("IsSoftKeyColor", "IsNotKeyColor"),
        (0.247, 0.686, 0.667),
        "Tween / expression state when you are between keys.",
    ),
    Binding(
        "Parameter States",
        "Pending changes",
        ("PendingColor", "ParmFieldKeyedBG", "ParmFieldKeyframeBG", "ParmFieldKeyframedBG", "ParmFieldAnimatedBG", "ParmKeyedBG"),
        (0.216, 0.467, 0.392),
        "Changed animated parameter that has not been committed as a key.",
    ),
    Binding(
        "Parameter States",
        "Override by CHOP",
        ("OverrideColor", "ParmFieldOverrideBG", "ParmFieldOverrideColor", "ParmOverrideBG"),
        (0.29, 0.435, 0.643),
        "Override / CHOP-driven state. Orange in many default Houdini themes.",
    ),
    Binding(
        "Parameter States",
        "Other language",
        ("OtherLanguageColor",),
        (0.29, 0.435, 0.643),
        "Usually Python expression when the node default is HScript.",
    ),
    Binding(
        "Parameter States",
        "Reference / non-default accent",
        ("NonDefAccentColor", "ChanRefAccentColor", "ParmFieldReferenceBG", "ParmFieldReferenceColor", "ParmFieldReferencedBG", "ParmReferenceBG"),
        (0.922, 0.286, 0.404),
        "Accent and reference colors used around non-default and ch() style parameters.",
    ),
    Binding(
        "Parameter States",
        "Locked parameter",
        ("LockedColor", "ChannelLockedColor"),
        (0.467, 0.596, 0.659),
        "Optional helper state for lock()/locked parameters.",
    ),
    Binding(
        "Slider",
        "Slider accent",
        ("SliderAdvancedGroove", "SliderAdvancedBevel"),
        (0.247, 0.686, 0.667),
        "Main line color inside parameter sliders.",
    ),
    Binding("Slider", "Slider thumb hi", ("SliderThumbGradHi",), (0.34, 0.37, 0.39), "Top part of the thumb."),
    Binding("Slider", "Slider thumb low", ("SliderThumbGradLow",), (0.23, 0.25, 0.27), "Bottom part of the thumb."),
    Binding("Slider", "Slider tick", ("SliderTick",), (0.31, 0.33, 0.35), "Tick marks and subtle scale lines."),
    Binding(
        "Keyframe Buttons",
        "Keyframe dot",
        ("KeyframeButtonCircleKey",),
        (0.98, 0.573, 0.69),
        "The main keyframe dot / marker color.",
    ),
    Binding(
        "Keyframe Buttons",
        "Pending key dot",
        ("KeyframeButtonCirclePending",),
        (0.502, 0.502, 0.502),
        "Pending keyframe dot color.",
    ),
    Binding(
        "Keyframe Buttons",
        "Animated no-key dot",
        ("KeyframeButtonCircleNoKey",),
        (0.247, 0.686, 0.667),
        "Animated but not currently on a key.",
    ),
    Binding(
        "Keyframe Buttons",
        "Some-key dot",
        ("KeyframeButtonCircleSomeKey",),
        (0.55, 0.51, 0.20),
        "Subtle mixed / secondary keyframe state.",
    ),
    Binding("Syntax / Text", "Function syntax", ("ParmSyntaxFuncColor",), (0.286, 0.784, 0.761), "Function name color in expressions."),
    Binding("Syntax / Text", "Reference syntax", ("ParmSyntaxRefColor",), (0.922, 0.286, 0.404), "Reference color in expressions."),
    Binding("Syntax / Text", "Textbox background", ("TextboxBG",), (0.027, 0.035, 0.039), "Default parameter text box background."),
    Binding("Syntax / Text", "UI text", ("ButtonText",), (0.949, 0.996, 1.0), "General text color used in previews."),
    Binding("Parameter Groups", "Group header base", ("GroupHeader0", "GroupHeaderTop0"), (0.341, 0.478, 0.533), "Default parameter group header background."),
    Binding("Parameter Groups", "Group header hover", ("GroupHeaderHi0", "GroupHeaderHiTop0"), (0.255, 0.388, 0.404), "Highlighted / hovered parameter group header background."),
    Binding("Parameter Groups", "Group header open", ("GroupHeaderOpen0", "GroupHeaderOpenTop0"), (0.333, 0.451, 0.459), "Expanded parameter group header background."),
    Binding("Parameter Groups", "Group header disabled", ("GroupHeaderDisabled0", "GroupHeaderDisabledTop0"), (0.20, 0.20, 0.20), "Disabled group header background."),
    Binding("Parameter Groups", "Pane header hi", ("PaneHeaderGradHi",), (0.204, 0.22, 0.227), "Top part of pane / tab header gradient."),
    Binding("Parameter Groups", "Pane header low", ("PaneHeaderGradLow",), (0.15, 0.17, 0.18), "Bottom part of pane / tab header gradient."),
    Binding("Parameter Groups", "Tab low / inactive", ("ButtonNonActiveGradLow",), (0.14, 0.15, 0.16), "Inactive tab / subdued pane chrome background."),
    Binding("Menus", "Menu background", ("MenuBG",), (0.23, 0.23, 0.23), "Popup menu background."),
    Binding("Menus", "Menu text", ("MenuText",), (0.80, 0.80, 0.80), "Default menu text color."),
    Binding("Menus", "Menu hover", ("MenuHighlight",), (0.58, 0.58, 0.58), "Hovered menu row background."),
    Binding("Menus", "Menu selected background", ("MenuSelectedBG",), (0.992, 0.573, 0.0), "Selected / active menu background for top menus and popup rows."),
    Binding("Menus", "Menu selected text", ("MenuTextSelected",), (1.00, 1.00, 1.00), "Text color on selected menu items."),
    Binding("Menus", "Menu title background", ("MenuTitleBG",), (0.17, 0.17, 0.17), "Top title/menu strip background."),
    Binding("Channel Editor", "Background", ("ChannelEditorBackground",), (0.0, 0.0, 0.0), "Channel editor / animation editor background."),
    Binding("Channel Editor", "Grid", ("ChannelEditorGridLine",), (0.27, 0.29, 0.31), "Main channel editor grid line."),
    Binding("Channel Editor", "Dashed grid", ("ChannelEditorGridDashedLine",), (0.22, 0.24, 0.26), "Secondary dashed grid line."),
    Binding("Channel Editor", "Selected handle", ("ChannelEditorHandleSelected",), (0.39, 0.66, 0.65), "Current selected key / handle color in the graph editor."),
    Binding("Channel Editor", "Current frame bar", ("DopeSheetCurrentFrameBG",), (0.471, 0.694, 0.773), "Current frame highlight in dope sheet style areas."),
    Binding("Node Graph", "Background", ("GraphBackground",), (0.18, 0.184, 0.196), "Node graph background."),
    Binding("Node Graph", "Grid lines", ("GraphGridLines",), (0.28, 0.30, 0.32), "Primary graph grid."),
    Binding("Node Graph", "Grid points", ("GraphGridPoints",), (0.22, 0.24, 0.25), "Secondary graph grid points."),
    Binding("Node Graph", "Wire", ("GraphWire",), (0.51, 0.627, 0.675), "Node wire color in the preview."),
    Binding("Node Graph", "Connector dot", ("GraphConnector",), (0.525, 0.678, 0.835), "Port / connector dot color on nodes."),
    Binding("Node Graph", "Connector label", ("GraphConnectorLabel",), (0.863, 0.847, 0.82), "Small label color near connectors."),
    Binding("Node Graph", "Connector error", ("GraphConnectorError",), (0.894, 0.373, 0.373), "Error connector / invalid port color."),
    Binding("Node Graph", "Node border", ("GraphItemBorder",), (0.212, 0.427, 0.604), "Node outline color."),
    Binding("Node Graph", "Node current outline", ("GraphItemCurrent",), (0.996, 0.38, 0.549), "Bright outline for the active/current node."),
    Binding("Node Graph", "Node selected outline", ("GraphItemSelection",), (0.988, 0.729, 0.055), "Selected node outline color."),
    Binding("Node Graph", "Node selection contrast", ("GraphItemSelectionContrast",), (0.0, 0.0, 0.0), "Contrast color used against selected node outlines."),
    Binding("Node Graph", "Connected wire highlight", ("GraphWireNodeSelection",), (0.996, 0.463, 0.773), "Highlight color for wires adjacent to the selected node."),
    Binding("Node Graph", "Wire selected", ("GraphWireSelection",), (0.906, 0.004, 0.227), "Explicitly selected wire highlight color."),
    Binding("Node Graph", "Node text", ("GraphNameText",), (0.86, 0.88, 0.89), "Node title text."),
    Binding("Node Graph", "Node type text", ("GraphNodeTypeText",), (0.61, 0.65, 0.68), "Secondary node type label text."),
    Binding("Channel Families", "Green family 1", ("ChannelColorGreen1",), (0.29, 0.871, 0.502), "Channel naming family used by y / g suffixes."),
    Binding("Channel Families", "Green family 2", ("ChannelColorGreen2",), (0.639, 0.902, 0.208), "Alternative green family tone."),
    Binding("Channel Families", "Green family 3", ("ChannelColorGreen3",), (0.204, 0.827, 0.6), "Alternative green family tone."),
    Binding("Channel Families", "Green family 4", ("ChannelColorGreen4",), (0.176, 0.831, 0.749), "Alternative green family tone."),
    Binding("Channel Families", "Green family 5", ("ChannelColorGreen5",), (0.086, 0.639, 0.29), "Alternative green family tone."),
)


SECTION_ORDER = []
for _binding in BINDINGS:
    if _binding.section not in SECTION_ORDER:
        SECTION_ORDER.append(_binding.section)

KEY_TO_PRIMARY: dict[str, str] = {}
for _binding in BINDINGS:
    for _key in _binding.keys:
        KEY_TO_PRIMARY.setdefault(_key, _binding.primary_key)


def parse_houdini_dir_version(name: str) -> tuple[int, ...]:
    lowered = name.lower()
    if not lowered.startswith("houdini"):
        return ()
    parts = re.findall(r"\d+", lowered[len("houdini"):])
    if not parts:
        return ()
    return tuple(int(part) for part in parts)


def find_houdini_config_dirs() -> list[Path]:
    candidates: list[Path] = []
    seen: set[str] = set()

    env_pref_dir = os.environ.get("HOUDINI_USER_PREF_DIR", "").strip()
    if env_pref_dir:
        config_dir = Path(env_pref_dir).expanduser() / "config"
        resolved = str(config_dir)
        if resolved not in seen:
            candidates.append(config_dir)
            seen.add(resolved)

    documents_dir = Path.home() / "Documents"
    if documents_dir.exists():
        for child in documents_dir.iterdir():
            if not child.is_dir():
                continue
            if not child.name.lower().startswith("houdini"):
                continue
            config_dir = child / "config"
            resolved = str(config_dir)
            if resolved in seen:
                continue
            candidates.append(config_dir)
            seen.add(resolved)

    return sorted(
        candidates,
        key=lambda path: (
            parse_houdini_dir_version(path.parent.name),
            path.parent.stat().st_mtime if path.parent.exists() else 0,
        ),
        reverse=True,
    )


class HCSThemeEditorApp:
    def __init__(self, root: tk.Tk, initial_path: Path | None) -> None:
        self.root = root
        self.root.title("Houdini HCS Theme Editor")
        self.root.geometry("1460x980")
        self.root.minsize(1180, 760)

        self.bg = "#1E2124"
        self.panel = "#272B30"
        self.panel_alt = "#23272B"
        self.line = "#373C42"
        self.text = "#D7DDE3"
        self.subtle = "#96A0AA"

        self.root.configure(bg=self.bg)

        self.document: HCSDocument | None = None
        self.current_colors: dict[str, tuple[float, float, float]] = {}
        self.entry_vars: dict[str, tk.StringVar] = {}
        self.entry_widgets: dict[str, tk.Entry] = {}
        self.swatches: dict[str, tk.Label] = {}
        self.status_var = tk.StringVar(value="Ready.")
        self.path_var = tk.StringVar()
        self.config_path_var = tk.StringVar()
        self.family_seed_var = tk.StringVar(value="#34D399")
        self.preview_canvases: dict[str, tk.Canvas] = {}
        self.detected_config_dirs: list[Path] = []
        self.family_seed_entry: tk.Entry | None = None
        self.family_seed_swatch: tk.Label | None = None
        self.document_is_generated = False

        self._build_ui()
        self.detect_houdini_config_dirs(initial_hint=initial_path)
        if initial_path is not None:
            self.load_document(initial_path)
        else:
            self.create_new_overlay_document(update_status=False)

    def _build_ui(self) -> None:
        toolbar = tk.Frame(self.root, bg=self.panel, padx=12, pady=10)
        toolbar.pack(fill="x")

        tk.Label(toolbar, text="Theme File", bg=self.panel, fg=self.text, font=("Segoe UI", 10, "bold")).pack(side="left")

        path_entry = tk.Entry(
            toolbar,
            textvariable=self.path_var,
            bg=self.panel_alt,
            fg=self.text,
            insertbackground=self.text,
            relief="flat",
            width=70,
            font=("Consolas", 10),
        )
        path_entry.pack(side="left", fill="x", expand=True, padx=(10, 8))

        self._make_toolbar_button(toolbar, "New Overlay", self.create_new_overlay_document)
        self._make_toolbar_button(toolbar, "Browse", self.browse_file)
        self._make_toolbar_button(toolbar, "Load", self.reload_file)
        self._make_toolbar_button(toolbar, "Save", self.save_file)
        self._make_toolbar_button(toolbar, "Save As", self.save_as)

        deploy_bar = tk.Frame(self.root, bg=self.panel_alt, padx=12, pady=8)
        deploy_bar.pack(fill="x", padx=10, pady=(0, 8))

        tk.Label(deploy_bar, text="Houdini Config", bg=self.panel_alt, fg=self.text, font=("Segoe UI", 10, "bold")).pack(side="left")

        config_entry = tk.Entry(
            deploy_bar,
            textvariable=self.config_path_var,
            state="readonly",
            readonlybackground=self.bg,
            fg=self.text,
            relief="flat",
            width=70,
            font=("Consolas", 10),
        )
        config_entry.pack(side="left", fill="x", expand=True, padx=(10, 8))

        self._make_toolbar_button(deploy_bar, "Detect", self.detect_houdini_config_dirs)
        self._make_toolbar_button(deploy_bar, "Deploy to Config", self.deploy_to_detected_config)

        body = tk.PanedWindow(self.root, sashwidth=6, bg=self.bg, orient="horizontal")
        body.pack(fill="both", expand=True, padx=10, pady=(8, 10))

        control_shell = tk.Frame(body, bg=self.panel, width=560)
        preview_shell = tk.Frame(body, bg=self.panel)
        body.add(control_shell, minsize=420)
        body.add(preview_shell, minsize=520)

        self.controls = ScrollableFrame(control_shell, self.panel)
        self.controls.pack(fill="both", expand=True)

        tk.Label(
            self.controls.inner,
            text="Edit colors as hex. Pick a swatch to choose visually. Save writes the active values back into the .hcs file.",
            bg=self.panel,
            fg=self.subtle,
            justify="left",
            wraplength=500,
            font=("Segoe UI", 10),
            padx=14,
            pady=14,
        ).pack(fill="x")

        for section in SECTION_ORDER:
            self._build_section(section)

        preview_header = tk.Frame(preview_shell, bg=self.panel, padx=14, pady=12)
        preview_header.pack(fill="x")
        tk.Label(preview_header, text="Preview", bg=self.panel, fg=self.text, font=("Segoe UI", 12, "bold")).pack(anchor="w")
        tk.Label(
            preview_header,
            text="These are simplified demos of the parameter editor, slider strip, channel editor, and node graph.",
            bg=self.panel,
            fg=self.subtle,
            wraplength=780,
            justify="left",
            font=("Segoe UI", 10),
        ).pack(anchor="w", pady=(4, 0))

        preview_scroll = ScrollableFrame(preview_shell, self.panel)
        preview_scroll.pack(fill="both", expand=True)
        self._add_preview_canvas(preview_scroll.inner, "menus", 780, 180, "Menus")
        self._add_preview_canvas(preview_scroll.inner, "parameter", 780, 300, "Parameter States")
        self._add_preview_canvas(preview_scroll.inner, "slider", 780, 180, "Slider / Keyframes")
        self._add_preview_canvas(preview_scroll.inner, "channel", 780, 220, "Channel Editor")
        self._add_preview_canvas(preview_scroll.inner, "graph", 780, 380, "Node Graph")

        tk.Label(
            self.root,
            textvariable=self.status_var,
            bg=self.panel,
            fg=self.subtle,
            anchor="w",
            padx=12,
            pady=8,
            font=("Segoe UI", 9),
        ).pack(fill="x", side="bottom")

    def _make_toolbar_button(self, master: tk.Misc, text: str, command) -> tk.Button:
        button = tk.Button(
            master,
            text=text,
            command=command,
            bg=self.panel_alt,
            fg=self.text,
            activebackground=self.line,
            activeforeground=self.text,
            relief="flat",
            padx=12,
            pady=6,
            font=("Segoe UI", 9),
            bd=0,
            highlightthickness=0,
        )
        button.pack(side="left", padx=(0, 8))
        return button

    def _build_section(self, section: str) -> None:
        frame = tk.LabelFrame(
            self.controls.inner,
            text=section,
            bg=self.panel_alt,
            fg=self.text,
            font=("Segoe UI", 10, "bold"),
            padx=12,
            pady=12,
            bd=1,
            relief="solid",
            highlightbackground=self.line,
            highlightcolor=self.line,
        )
        frame.pack(fill="x", padx=12, pady=(0, 12))
        if section == "Channel Families":
            self._build_family_palette_generator(frame)
        for binding in (item for item in BINDINGS if item.section == section):
            self._build_binding_row(frame, binding)

    def _build_family_palette_generator(self, master: tk.Misc) -> None:
        block = tk.Frame(master, bg=self.bg, padx=12, pady=12, bd=1, relief="solid", highlightbackground=self.line, highlightcolor=self.line)
        block.pack(fill="x", pady=(0, 12))

        tk.Label(block, text="Generate family palette from one base color", bg=self.bg, fg=self.text, anchor="w", font=("Segoe UI", 10, "bold")).pack(anchor="w")
        tk.Label(
            block,
            text="Pick one base color, then generate 5 linked channel-family colors automatically.",
            bg=self.bg,
            fg=self.subtle,
            anchor="w",
            justify="left",
            wraplength=470,
            font=("Segoe UI", 9),
        ).pack(anchor="w", pady=(4, 10))

        row = tk.Frame(block, bg=self.bg)
        row.pack(fill="x")

        tk.Label(row, text="Base family color", bg=self.bg, fg=self.text, width=22, anchor="w", font=("Segoe UI", 10, "bold")).pack(side="left")

        self.family_seed_entry = tk.Entry(
            row,
            textvariable=self.family_seed_var,
            bg=self.panel_alt,
            fg=self.text,
            insertbackground=self.text,
            relief="flat",
            width=12,
            font=("Consolas", 10),
        )
        self.family_seed_entry.pack(side="left", padx=(0, 8))
        self.family_seed_entry.bind("<Return>", lambda event: self.commit_family_seed())
        self.family_seed_entry.bind("<FocusOut>", lambda event: self.commit_family_seed())

        self.family_seed_swatch = tk.Label(row, text="    ", bg=self.family_seed_var.get(), relief="solid", bd=1, cursor="hand2")
        self.family_seed_swatch.pack(side="left", padx=(0, 8))
        self.family_seed_swatch.bind("<Button-1>", lambda event: self.pick_family_seed_color())

        tk.Button(
            row,
            text="Pick",
            command=self.pick_family_seed_color,
            bg=self.panel_alt,
            fg=self.text,
            activebackground=self.line,
            activeforeground=self.text,
            relief="flat",
            padx=10,
            pady=4,
            bd=0,
            highlightthickness=0,
        ).pack(side="left", padx=(0, 8))

        tk.Button(
            row,
            text="Use Green 3",
            command=self.seed_family_from_current,
            bg=self.panel_alt,
            fg=self.text,
            activebackground=self.line,
            activeforeground=self.text,
            relief="flat",
            padx=10,
            pady=4,
            bd=0,
            highlightthickness=0,
        ).pack(side="left", padx=(0, 8))

        tk.Button(
            row,
            text="Generate Palette",
            command=self.generate_channel_family_palette,
            bg=self.panel,
            fg=self.text,
            activebackground=self.line,
            activeforeground=self.text,
            relief="flat",
            padx=12,
            pady=4,
            bd=0,
            highlightthickness=0,
        ).pack(side="left")

    def _build_binding_row(self, master: tk.Misc, binding: Binding) -> None:
        row = tk.Frame(master, bg=self.panel_alt, pady=6)
        row.pack(fill="x")

        top = tk.Frame(row, bg=self.panel_alt)
        top.pack(fill="x")

        tk.Label(top, text=binding.label, bg=self.panel_alt, fg=self.text, width=22, anchor="w", font=("Segoe UI", 10, "bold")).pack(side="left")

        variable = tk.StringVar()
        entry = tk.Entry(
            top,
            textvariable=variable,
            bg=self.bg,
            fg=self.text,
            insertbackground=self.text,
            relief="flat",
            width=12,
            font=("Consolas", 10),
        )
        entry.pack(side="left", padx=(0, 8))
        entry.bind("<Return>", lambda event, key=binding.primary_key: self.commit_entry(key))
        entry.bind("<FocusOut>", lambda event, key=binding.primary_key: self.commit_entry(key))

        swatch = tk.Label(top, text="    ", bg=rgb_to_hex(binding.fallback), relief="solid", bd=1, cursor="hand2")
        swatch.pack(side="left", padx=(0, 8))
        swatch.bind("<Button-1>", lambda event, item=binding: self.pick_color(item))

        tk.Button(
            top,
            text="Pick",
            command=lambda item=binding: self.pick_color(item),
            bg=self.bg,
            fg=self.text,
            activebackground=self.line,
            activeforeground=self.text,
            relief="flat",
            padx=10,
            pady=4,
            bd=0,
            highlightthickness=0,
        ).pack(side="left")

        tk.Label(
            row,
            text=", ".join(binding.keys),
            bg=self.panel_alt,
            fg=self.subtle,
            anchor="w",
            justify="left",
            wraplength=470,
            font=("Consolas", 8),
        ).pack(fill="x", pady=(3, 0))

        tk.Label(
            row,
            text=binding.note,
            bg=self.panel_alt,
            fg=self.subtle,
            anchor="w",
            justify="left",
            wraplength=470,
            font=("Segoe UI", 9),
        ).pack(fill="x", pady=(1, 0))

        self.entry_vars[binding.primary_key] = variable
        self.entry_widgets[binding.primary_key] = entry
        self.swatches[binding.primary_key] = swatch

    def _add_preview_canvas(self, master: tk.Misc, key: str, width: int, height: int, title: str) -> None:
        wrapper = tk.Frame(master, bg=self.panel, padx=14, pady=12)
        wrapper.pack(fill="x")
        tk.Label(wrapper, text=title, bg=self.panel, fg=self.text, anchor="w", font=("Segoe UI", 10, "bold")).pack(anchor="w", pady=(0, 6))
        canvas = tk.Canvas(wrapper, width=width, height=height, bg=self.bg, highlightbackground=self.line, highlightcolor=self.line, bd=1, relief="solid")
        canvas.pack(fill="x", expand=True)
        canvas.bind("<Configure>", lambda event: self.redraw_previews())
        self.preview_canvases[key] = canvas

    def create_new_overlay_document(self, update_status: bool = True) -> None:
        self.document = HCSDocument.new_overlay()
        self.document_is_generated = True
        self.path_var.set(str(self.document.path))
        self.current_colors.clear()
        for binding in BINDINGS:
            color = self._resolve_binding_color(binding)
            self.current_colors[binding.primary_key] = color
            self._set_binding_ui(binding.primary_key, color)
        self.seed_family_from_current(update_status=False)
        self.redraw_previews()
        if update_status:
            self.status_var.set("Created a new overlay theme. Save As or Deploy to write it.")

    def browse_file(self) -> None:
        selected = filedialog.askopenfilename(
            title="Open Houdini .hcs file",
            filetypes=[("Houdini Color Scheme", "*.hcs"), ("All files", "*.*")],
        )
        if selected:
            self.load_document(Path(selected))

    def reload_file(self) -> None:
        if not self.path_var.get().strip():
            self.browse_file()
            return
        self.load_document(Path(self.path_var.get().strip()))

    def load_document(self, path: Path) -> None:
        try:
            self.document = HCSDocument.load(path)
        except Exception as exc:  # noqa: BLE001
            messagebox.showerror("Load failed", f"Could not load file:\n{path}\n\n{exc}")
            return

        self.document_is_generated = False
        self.path_var.set(str(path))
        self.current_colors.clear()
        for binding in BINDINGS:
            color = self._resolve_binding_color(binding)
            self.current_colors[binding.primary_key] = color
            self._set_binding_ui(binding.primary_key, color)
        self.seed_family_from_current(update_status=False)
        self.redraw_previews()
        self.status_var.set(f"Loaded {path}")

    def detect_houdini_config_dirs(self, initial_hint: Path | None = None) -> None:
        paths = find_houdini_config_dirs()
        preferred = None

        if initial_hint is not None:
            hinted = initial_hint.expanduser().resolve()
            for path in paths:
                try:
                    if path.resolve() == hinted.parent.resolve():
                        preferred = path
                        break
                except OSError:
                    continue

        self.detected_config_dirs = paths
        if preferred is None and paths:
            preferred = paths[0]

        if preferred is not None:
            self.config_path_var.set(str(preferred))
            if len(paths) > 1:
                self.status_var.set(f"Detected {len(paths)} Houdini config folders. Using {preferred}")
            else:
                self.status_var.set(f"Detected Houdini config folder: {preferred}")
        else:
            self.config_path_var.set("")
            self.status_var.set("No Houdini config folder detected yet.")

    def _resolve_binding_color(self, binding: Binding) -> tuple[float, float, float]:
        if self.document is not None:
            for key in binding.keys:
                parsed = self.document.get_color(key)
                if parsed is not None:
                    return parsed
        return binding.fallback

    def _set_binding_ui(self, primary_key: str, color: tuple[float, float, float]) -> None:
        self.entry_vars[primary_key].set(rgb_to_hex(color))
        self.swatches[primary_key].configure(bg=rgb_to_hex(color))
        self.entry_widgets[primary_key].configure(highlightthickness=0)

    def _set_family_seed_ui(self, color: tuple[float, float, float]) -> None:
        hex_color = rgb_to_hex(color)
        self.family_seed_var.set(hex_color)
        if self.family_seed_swatch is not None:
            self.family_seed_swatch.configure(bg=hex_color)
        if self.family_seed_entry is not None:
            self.family_seed_entry.configure(highlightthickness=0)

    def commit_family_seed(self) -> None:
        text = self.family_seed_var.get().strip()
        if not text:
            return
        if not text.startswith("#"):
            text = "#" + text
        try:
            color = hex_to_rgb(text)
        except ValueError:
            if self.family_seed_entry is not None:
                self.family_seed_entry.configure(highlightbackground="#E14640", highlightcolor="#E14640", highlightthickness=1)
            self.status_var.set(f"Invalid family seed color: {self.family_seed_var.get().strip()}")
            return
        self._set_family_seed_ui(color)
        self.status_var.set(f"Family seed set to {rgb_to_hex(color)}")

    def pick_family_seed_color(self) -> None:
        initial = self.family_seed_var.get().strip() or "#34D399"
        if not initial.startswith("#"):
            initial = "#" + initial
        rgb_tuple, hex_value = colorchooser.askcolor(color=initial, title="Base family color")
        if not hex_value:
            return
        del rgb_tuple
        self._set_family_seed_ui(hex_to_rgb(hex_value))
        self.status_var.set(f"Family seed picked: {hex_value.upper()}")

    def seed_family_from_current(self, update_status: bool = True) -> None:
        color = self.current_colors.get("ChannelColorGreen3", hex_to_rgb("#34D399"))
        self._set_family_seed_ui(color)
        if update_status:
            self.status_var.set(f"Family seed synced from Green family 3: {rgb_to_hex(color)}")

    def generate_channel_family_palette(self) -> None:
        self.commit_family_seed()
        text = self.family_seed_var.get().strip()
        if not text:
            return
        if not text.startswith("#"):
            text = "#" + text
        try:
            base_color = hex_to_rgb(text)
        except ValueError:
            return

        palette = build_channel_family_palette(base_color)
        keys = [
            "ChannelColorGreen1",
            "ChannelColorGreen2",
            "ChannelColorGreen3",
            "ChannelColorGreen4",
            "ChannelColorGreen5",
        ]
        for key, color in zip(keys, palette, strict=False):
            primary_key = KEY_TO_PRIMARY.get(key, key)
            self.current_colors[primary_key] = color
            self._set_binding_ui(primary_key, color)

        self.redraw_previews()
        self.status_var.set(f"Generated channel family palette from {rgb_to_hex(base_color)}")

    def commit_entry(self, primary_key: str) -> None:
        text = self.entry_vars[primary_key].get().strip()
        if not text:
            return
        if not text.startswith("#"):
            text = "#" + text
        try:
            color = hex_to_rgb(text)
        except ValueError:
            self.entry_widgets[primary_key].configure(highlightbackground="#E14640", highlightcolor="#E14640", highlightthickness=1)
            self.status_var.set(f"Invalid color for {primary_key}: {self.entry_vars[primary_key].get().strip()}")
            return
        self.current_colors[primary_key] = color
        self._set_binding_ui(primary_key, color)
        self.redraw_previews()
        self.status_var.set(f"Updated {primary_key} to {rgb_to_hex(color)}")

    def pick_color(self, binding: Binding) -> None:
        initial = rgb_to_hex(self.current_colors.get(binding.primary_key, binding.fallback))
        rgb_tuple, hex_value = colorchooser.askcolor(color=initial, title=binding.label)
        if not hex_value:
            return
        del rgb_tuple
        color = hex_to_rgb(hex_value)
        self.current_colors[binding.primary_key] = color
        self._set_binding_ui(binding.primary_key, color)
        self.redraw_previews()
        self.status_var.set(f"Picked {binding.label}: {hex_value.upper()}")

    def _apply_current_colors_to_document(self) -> bool:
        if self.document is None:
            self.create_new_overlay_document(update_status=False)
            if self.document is None:
                messagebox.showinfo("No file loaded", "Create or load a .hcs file first.")
                return False
        for binding in BINDINGS:
            color = self.current_colors.get(binding.primary_key, binding.fallback)
            for key in binding.keys:
                self.document.set_color(key, color)
        return True

    def save_file(self) -> None:
        if not self._apply_current_colors_to_document():
            return
        if self.document_is_generated:
            self.save_as()
            return
        try:
            assert self.document is not None
            scheme_name = self.document.sync_scheme_name_to_path(self.document.path)
            self.document.save()
        except Exception as exc:  # noqa: BLE001
            messagebox.showerror("Save failed", f"Could not save file:\n{self.document.path}\n\n{exc}")
            return
        self.status_var.set(f"Saved {self.document.path} with Scheme: {scheme_name}")
        messagebox.showinfo("Saved", f"Saved theme file:\n{self.document.path}\n\nScheme: {scheme_name}")

    def save_as(self) -> None:
        if not self._apply_current_colors_to_document():
            return
        target = filedialog.asksaveasfilename(
            title="Save Houdini .hcs file",
            defaultextension=".hcs",
            filetypes=[("Houdini Color Scheme", "*.hcs"), ("All files", "*.*")],
            initialfile=self.document.path.name,
        )
        if not target:
            return
        try:
            assert self.document is not None
            scheme_name = self.document.sync_scheme_name_to_path(target)
            self.document.save(target)
        except Exception as exc:  # noqa: BLE001
            messagebox.showerror("Save failed", f"Could not save file:\n{target}\n\n{exc}")
            return
        self.document_is_generated = False
        self.path_var.set(str(Path(target)))
        self.status_var.set(f"Saved as {target} with Scheme: {scheme_name}")
        messagebox.showinfo("Saved", f"Saved theme file:\n{target}\n\nScheme: {scheme_name}")

    def deploy_to_detected_config(self) -> None:
        if not self._apply_current_colors_to_document():
            return

        config_text = self.config_path_var.get().strip()
        if not config_text:
            self.detect_houdini_config_dirs()
            config_text = self.config_path_var.get().strip()
            if not config_text:
                messagebox.showwarning(
                    "Config not found",
                    "Could not automatically find a Houdini config folder.\n"
                    "Make sure you have launched Houdini at least once, or save manually.",
                )
                return

        config_dir = Path(config_text)
        theme_name = self.document.path.name if self.document is not None else f"{DEFAULT_NEW_THEME_NAME}.hcs"
        target = config_dir / theme_name

        try:
            config_dir.mkdir(parents=True, exist_ok=True)
            assert self.document is not None
            scheme_name = self.document.sync_scheme_name_to_path(target)
            self.document.write_to(target)
        except Exception as exc:  # noqa: BLE001
            messagebox.showerror("Deploy failed", f"Could not deploy theme to:\n{target}\n\n{exc}")
            return

        self.document.path = target
        self.document_is_generated = False
        self.path_var.set(str(target))
        self.status_var.set(f"Deployed theme to {target}")
        messagebox.showinfo(
            "Theme deployed",
            "Theme file copied to Houdini config:\n"
            f"{target}\n\n"
            f"Scheme: {scheme_name}\n\n"
            "In Houdini, click Reload in Color Settings or restart Houdini.",
        )

    def get_binding_color(self, key: str, fallback: tuple[float, float, float]) -> tuple[float, float, float]:
        primary_key = KEY_TO_PRIMARY.get(key, key)
        return self.current_colors.get(primary_key, fallback)

    def redraw_previews(self) -> None:
        self._draw_menu_preview()
        self._draw_parameter_preview()
        self._draw_slider_preview()
        self._draw_channel_preview()
        self._draw_graph_preview()

    def _draw_menu_preview(self) -> None:
        canvas = self.preview_canvases["menus"]
        canvas.delete("all")
        width = max(canvas.winfo_width(), 780)
        height = max(canvas.winfo_height(), 180)

        menu_bg = self.get_binding_color("MenuBG", (0.23, 0.23, 0.23))
        menu_text = self.get_binding_color("MenuText", (0.80, 0.80, 0.80))
        menu_hover = self.get_binding_color("MenuHighlight", (0.58, 0.58, 0.58))
        menu_selected_bg = self.get_binding_color("MenuSelectedBG", (0.70, 0.40, 0.00))
        menu_selected_text = self.get_binding_color("MenuTextSelected", (1.0, 1.0, 1.0))
        menu_title_bg = self.get_binding_color("MenuTitleBG", (0.17, 0.17, 0.17))

        canvas.create_rectangle(0, 0, width, height, fill=self.bg, outline="")
        canvas.create_text(20, 18, anchor="nw", text="Menu preview", fill=self.subtle, font=("Segoe UI", 10, "bold"))

        top_y0 = 42
        top_y1 = 76
        canvas.create_rectangle(20, top_y0, width - 20, top_y1, fill=rgb_to_hex(menu_title_bg), outline=self.line)

        items = [("File", False), ("Edit", True), ("Render", False), ("Assets", False), ("Windows", False)]
        x = 34
        for label, selected in items:
            pad = 16 + len(label) * 7
            fill = rgb_to_hex(menu_selected_bg) if selected else rgb_to_hex(menu_title_bg)
            text_fill = rgb_to_hex(menu_selected_text) if selected else rgb_to_hex(menu_text)
            canvas.create_rectangle(x - 8, top_y0 + 2, x + pad, top_y1 - 2, fill=fill, outline="")
            canvas.create_text(x, top_y0 + 9, anchor="nw", text=label, fill=text_fill, font=("Segoe UI", 11))
            x += pad + 14

        menu_x0 = 34
        menu_y0 = top_y1
        menu_x1 = 250
        menu_y1 = 158
        canvas.create_rectangle(menu_x0, menu_y0, menu_x1, menu_y1, fill=rgb_to_hex(menu_bg), outline=self.line)

        rows = [
            ("Undo Change selection", True, False),
            ("Can't redo", False, False),
            ("Undo History...", False, True),
        ]
        row_h = 32
        for index, (label, selected, disabled) in enumerate(rows):
            y0 = menu_y0 + index * row_h
            y1 = y0 + row_h
            fill = menu_selected_bg if selected else menu_bg
            canvas.create_rectangle(menu_x0 + 1, y0 + 1, menu_x1 - 1, y1, fill=rgb_to_hex(fill), outline="")
            if disabled:
                text_fill = "#8E9398"
            else:
                text_fill = rgb_to_hex(menu_selected_text) if selected else rgb_to_hex(menu_text)
            canvas.create_text(menu_x0 + 14, y0 + 8, anchor="nw", text=label, fill=text_fill, font=("Segoe UI", 10))

        hover_x0 = 300
        hover_x1 = width - 24
        hover_y0 = 92
        hover_y1 = 124
        canvas.create_rectangle(hover_x0, hover_y0, hover_x1, hover_y1, fill=rgb_to_hex(menu_bg), outline=self.line)
        canvas.create_rectangle(hover_x0 + 1, hover_y0 + 1, hover_x1 - 1, hover_y1 - 1, fill=rgb_to_hex(menu_hover), outline="")
        canvas.create_text(hover_x0 + 12, hover_y0 + 7, anchor="nw", text="Hovered menu row sample", fill=rgb_to_hex(menu_text), font=("Segoe UI", 10))

    def _draw_parameter_preview(self) -> None:
        canvas = self.preview_canvases["parameter"]
        canvas.delete("all")
        width = max(canvas.winfo_width(), 780)
        height = max(canvas.winfo_height(), 300)

        ui_text = self.get_binding_color("ButtonText", (0.82, 0.84, 0.86))
        textbox_bg = self.get_binding_color("TextboxBG", (0.15, 0.16, 0.17))
        border = (0.27, 0.29, 0.31)
        group_base = self.get_binding_color("GroupHeader0", (0.20, 0.20, 0.20))
        group_hover = self.get_binding_color("GroupHeaderHi0", (0.32, 0.32, 0.32))
        group_open = self.get_binding_color("GroupHeaderOpen0", (0.31, 0.31, 0.31))
        expr = self.get_binding_color("IsKeyColor", hex_to_rgb("#49C8C2"))
        tween = self.get_binding_color("IsNotKeyColor", hex_to_rgb("#3FAFAA"))
        pending = self.get_binding_color("PendingColor", hex_to_rgb("#F3E16C"))
        override = self.get_binding_color("OverrideColor", hex_to_rgb("#EB4967"))
        other_lang = self.get_binding_color("OtherLanguageColor", hex_to_rgb("#EB4967"))
        accent = self.get_binding_color("NonDefAccentColor", hex_to_rgb("#EB4967"))

        canvas.create_rectangle(0, 0, width, height, fill=self.bg, outline="")
        canvas.create_text(20, 18, anchor="nw", text="Parameter editor state demo", fill=self.subtle, font=("Segoe UI", 10, "bold"))

        header_x0 = 20
        header_x1 = width - 24
        base_y = 46
        header_h = 30

        headers = [
            ("Base Group", group_open),
            ("Keep in Bounding Regions", group_base),
            ("Keep by Normals", group_hover),
        ]
        for index, (label, color) in enumerate(headers):
            y0 = base_y + index * 42
            y1 = y0 + header_h
            canvas.create_rectangle(header_x0, y0, header_x1, y1, fill=rgb_to_hex(color), outline="")
            canvas.create_text(header_x0 + 12, y0 + 8, anchor="nw", text=label, fill=rgb_to_hex(ui_text), font=("Segoe UI", 11, "bold"))

        fields = [
            ("Normal", textbox_bg, None, "0.25"),
            ("Expression / keyed", expr, accent, 'ch("height") / 2'),
            ("Animated / not on key", tween, None, 'ch("diameter") * ch("ratio")'),
            ("Pending changes", pending, None, "640"),
            ("Override by CHOP", override, None, "channel override"),
            ("Python / other lang", other_lang, accent, "hou.frame() * 0.5"),
        ]

        x = 20
        y = 176
        field_h = 34
        gap = 10

        for index, (label, bg_color, underline, value) in enumerate(fields):
            top = y + index * (field_h + gap)
            canvas.create_text(x, top + 6, anchor="nw", text=label, fill=rgb_to_hex(ui_text), font=("Segoe UI", 10))
            left = 210
            right = width - 24
            canvas.create_rectangle(left, top, right, top + field_h, fill=rgb_to_hex(bg_color), outline=rgb_to_hex(border))
            canvas.create_text(left + 10, top + 9, anchor="nw", text=value, fill="#F6F7F8", font=("Consolas", 10))
            if underline is not None:
                canvas.create_rectangle(left, top + field_h - 3, right, top + field_h, fill=rgb_to_hex(underline), outline="")

    def _draw_slider_preview(self) -> None:
        canvas = self.preview_canvases["slider"]
        canvas.delete("all")
        width = max(canvas.winfo_width(), 780)
        height = max(canvas.winfo_height(), 180)

        track = self.get_binding_color("SliderAdvancedGroove", hex_to_rgb("#3FAFAA"))
        tick = self.get_binding_color("SliderTick", (0.31, 0.33, 0.35))
        thumb_hi = self.get_binding_color("SliderThumbGradHi", (0.34, 0.37, 0.39))
        thumb_lo = self.get_binding_color("SliderThumbGradLow", (0.23, 0.25, 0.27))
        key = self.get_binding_color("KeyframeButtonCircleKey", hex_to_rgb("#F3E16C"))
        pending = self.get_binding_color("KeyframeButtonCirclePending", hex_to_rgb("#F3E16C"))
        no_key = self.get_binding_color("KeyframeButtonCircleNoKey", hex_to_rgb("#3FAFAA"))

        canvas.create_rectangle(0, 0, width, height, fill=self.bg, outline="")
        canvas.create_text(20, 18, anchor="nw", text="Slider and keyframe preview", fill=self.subtle, font=("Segoe UI", 10, "bold"))

        groove_y = 72
        groove_left = 24
        groove_right = width - 24

        for offset in range(0, 11):
            x = groove_left + (groove_right - groove_left) * offset / 10.0
            canvas.create_line(x, groove_y - 18, x, groove_y - 8, fill=rgb_to_hex(tick))

        canvas.create_line(groove_left, groove_y, groove_right, groove_y, fill="#17191B", width=8)
        canvas.create_line(groove_left, groove_y, groove_right - 120, groove_y, fill=rgb_to_hex(track), width=4)

        thumb_x = groove_right - 120
        canvas.create_rectangle(thumb_x - 6, groove_y - 18, thumb_x + 6, groove_y + 18, fill=rgb_to_hex(thumb_lo), outline=rgb_to_hex(thumb_hi))

        canvas.create_text(24, 110, anchor="nw", text="Keyframe states", fill=self.subtle, font=("Segoe UI", 9, "bold"))
        samples = [("No key", no_key), ("Key", key), ("Pending", pending)]
        sx = 24
        for label, color in samples:
            canvas.create_oval(sx, 136, sx + 18, 154, fill=rgb_to_hex(color), outline="")
            canvas.create_text(sx + 28, 136, anchor="nw", text=label, fill=self.text, font=("Segoe UI", 9))
            sx += 130

    def _draw_channel_preview(self) -> None:
        canvas = self.preview_canvases["channel"]
        canvas.delete("all")
        width = max(canvas.winfo_width(), 780)
        height = max(canvas.winfo_height(), 220)

        bg = self.get_binding_color("ChannelEditorBackground", (0.15, 0.16, 0.17))
        grid = self.get_binding_color("ChannelEditorGridLine", (0.27, 0.29, 0.31))
        dashed = self.get_binding_color("ChannelEditorGridDashedLine", (0.22, 0.24, 0.26))
        selected = self.get_binding_color("ChannelEditorHandleSelected", (0.39, 0.66, 0.65))
        frame_bar = self.get_binding_color("DopeSheetCurrentFrameBG", (0.28, 0.49, 0.53))
        green1 = self.get_binding_color("ChannelColorGreen1", hex_to_rgb("#4ADE80"))
        green4 = self.get_binding_color("ChannelColorGreen4", hex_to_rgb("#2DD4BF"))

        canvas.create_rectangle(0, 0, width, height, fill=rgb_to_hex(bg), outline="")
        canvas.create_text(20, 18, anchor="nw", text="Channel editor demo", fill=self.subtle, font=("Segoe UI", 10, "bold"))

        left = 24
        right = width - 24
        top = 42
        bottom = height - 24

        for step in range(6):
            y = top + (bottom - top) * step / 5.0
            canvas.create_line(left, y, right, y, fill=rgb_to_hex(grid))
        for step in range(1, 10):
            x = left + (right - left) * step / 10.0
            color = dashed if step % 2 else grid
            canvas.create_line(x, top, x, bottom, fill=rgb_to_hex(color), dash=(3, 5))

        frame_x = left + (right - left) * 0.62
        canvas.create_line(frame_x, top, frame_x, bottom, fill=rgb_to_hex(frame_bar), width=2)

        points1 = []
        points2 = []
        for index in range(11):
            x = left + (right - left) * index / 10.0
            y1 = top + 95 - ((index % 3) * 18) - (index * 1.5)
            y2 = top + 48 + ((index % 4) * 14)
            points1.append((x, y1))
            points2.append((x, y2))

        canvas.create_line(*[coord for point in points1 for coord in point], fill=rgb_to_hex(green1), width=2, smooth=True)
        canvas.create_line(*[coord for point in points2 for coord in point], fill=rgb_to_hex(green4), width=2, smooth=True)

        for x, y in (points1[3], points1[6], points2[5]):
            canvas.create_oval(x - 5, y - 5, x + 5, y + 5, fill=rgb_to_hex(selected), outline="")

    def _draw_graph_preview(self) -> None:
        canvas = self.preview_canvases["graph"]
        canvas.delete("all")
        width = max(canvas.winfo_width(), 780)
        height = max(canvas.winfo_height(), 380)

        bg = self.get_binding_color("GraphBackground", (0.16, 0.17, 0.18))
        grid_lines = self.get_binding_color("GraphGridLines", (0.28, 0.30, 0.32))
        grid_points = self.get_binding_color("GraphGridPoints", (0.22, 0.24, 0.25))
        wire = self.get_binding_color("GraphWire", (0.56, 0.67, 0.71))
        connector = self.get_binding_color("GraphConnector", (0.39, 0.63, 0.67))
        connector_label = self.get_binding_color("GraphConnectorLabel", (0.72, 0.76, 0.78))
        connector_error = self.get_binding_color("GraphConnectorError", (0.83, 0.43, 0.43))
        node_border = self.get_binding_color("GraphItemBorder", (0.08, 0.09, 0.10))
        node_current_outline = self.get_binding_color("GraphItemCurrent", (1.00, 0.83, 0.00))
        node_selected_outline = self.get_binding_color("GraphItemSelection", (0.93, 0.97, 0.11))
        node_selection_contrast = self.get_binding_color("GraphItemSelectionContrast", (0.0, 0.0, 0.0))
        wire_node_selection = self.get_binding_color("GraphWireNodeSelection", (0.93, 0.97, 0.11))
        wire_selection = self.get_binding_color("GraphWireSelection", (0.93, 0.97, 0.11))
        node_text = self.get_binding_color("GraphNameText", (0.86, 0.88, 0.89))
        node_type_text = self.get_binding_color("GraphNodeTypeText", (0.61, 0.65, 0.68))
        param_text = self.get_binding_color("ButtonText", (0.82, 0.84, 0.86))

        canvas.create_rectangle(0, 0, width, height, fill=rgb_to_hex(bg), outline="")
        canvas.create_text(20, 18, anchor="nw", text="Node graph demo", fill=self.subtle, font=("Segoe UI", 10, "bold"))

        for x in range(0, width, 40):
            canvas.create_line(x, 36, x, height, fill=rgb_to_hex(grid_lines))
        for y in range(36, height, 40):
            canvas.create_line(0, y, width, y, fill=rgb_to_hex(grid_lines))
        for x in range(20, width, 40):
            for y in range(56, height, 40):
                canvas.create_rectangle(x - 1, y - 1, x + 1, y + 1, fill=rgb_to_hex(grid_points), outline="")

        def draw_port(x: float, y: float, radius: float = 7.0, color: tuple[float, float, float] | None = None) -> None:
            fill = rgb_to_hex(color or connector)
            canvas.create_oval(x - radius, y - radius, x + radius, y + radius, fill=fill, outline="")

        def draw_node_body(
            x0: float,
            y0: float,
            x1: float,
            y1: float,
            *,
            current: bool = False,
            selected: bool = False,
            halo: bool = False,
        ) -> None:
            outer_fill = "#CFCFD0"
            inner_fill = "#EFEFEF"
            if halo:
                canvas.create_oval(
                    x0 - 28,
                    y0 - 28,
                    x1 + 28,
                    y1 + 28,
                    fill="#5D7FD0",
                    outline="",
                    stipple="gray50",
                )
                canvas.create_arc(
                    x0 - 22,
                    y0 - 22,
                    x1 + 22,
                    y1 + 22,
                    start=25,
                    extent=130,
                    style="arc",
                    outline="#60C5D8",
                    width=6,
                )
            if current:
                create_round_rect(
                    canvas,
                    x0 - 4,
                    y0 - 4,
                    x1 + 4,
                    y1 + 4,
                    16,
                    fill="",
                    outline=rgb_to_hex(node_current_outline),
                    width=2.5,
                )
            if selected:
                create_round_rect(
                    canvas,
                    x0 - 2,
                    y0 - 2,
                    x1 + 2,
                    y1 + 2,
                    15,
                    fill="",
                    outline=rgb_to_hex(node_selected_outline),
                    width=1.2,
                )
            create_round_rect(canvas, x0, y0, x1, y1, 14, fill=outer_fill, outline=rgb_to_hex(node_border), width=1.5)
            create_round_rect(canvas, x0 + 2, y0 + 2, x1 - 2, y1 - 2, 12, fill=inner_fill, outline="")
            for stripe_x in (x0 + 30, x0 + 58, x0 + 86):
                canvas.create_line(stripe_x, y0 + 4, stripe_x - 8, y1 - 4, fill="#B8B8B8", width=1)

        def draw_boolean_icon(cx: float, cy: float) -> None:
            canvas.create_oval(cx - 22, cy - 22, cx + 22, cy + 22, fill="#E4E4E4", outline="#B6B6B6", width=1.2)
            canvas.create_polygon(
                cx - 8, cy - 10,
                cx + 5, cy - 12,
                cx + 14, cy - 4,
                cx + 1, cy - 2,
                fill="#DADADA", outline="#A8A8A8", width=1
            )
            canvas.create_polygon(
                cx - 8, cy - 10,
                cx - 8, cy + 3,
                cx + 1, cy + 12,
                cx + 1, cy - 2,
                fill="#EDEDED", outline="#A8A8A8", width=1
            )
            canvas.create_polygon(
                cx + 1, cy - 2,
                cx + 14, cy - 4,
                cx + 14, cy + 9,
                cx + 1, cy + 12,
                fill="#C8CFD8", outline="#A8A8A8", width=1
            )

        def draw_simple_icon(cx: float, cy: float, kind: str) -> None:
            if kind == "group":
                canvas.create_oval(cx - 13, cy - 13, cx + 13, cy + 13, fill="#F7F2DA", outline="#F39C12", width=1.8)
            elif kind == "blast":
                canvas.create_polygon(
                    cx - 12, cy + 8, cx - 8, cy - 6, cx - 2, cy + 2,
                    cx + 2, cy - 8, cx + 7, cy + 2, cx + 12, cy - 5,
                    cx + 10, cy + 9,
                    fill="#F39C34", outline="#D36B00", width=1.0
                )
                canvas.create_rectangle(cx - 13, cy + 6, cx + 13, cy + 10, fill="#F39C34", outline="#D36B00", width=1.0)
            elif kind == "extrude":
                canvas.create_polygon(cx - 8, cy - 10, cx + 4, cy - 12, cx + 14, cy - 4, cx + 2, cy - 2, fill="#F7B733", outline="#C47F16", width=1)
                canvas.create_polygon(cx - 8, cy - 10, cx - 8, cy + 4, cx + 2, cy + 12, cx + 2, cy - 2, fill="#FFD46B", outline="#C47F16", width=1)
                canvas.create_polygon(cx + 2, cy - 2, cx + 14, cy - 4, cx + 14, cy + 10, cx + 2, cy + 12, fill="#E4A92C", outline="#C47F16", width=1)
                canvas.create_line(cx + 10, cy + 8, cx + 18, cy + 14, fill="#E14640", width=2)
            elif kind == "tube":
                create_round_rect(canvas, cx - 10, cy - 13, cx + 10, cy + 13, 8, fill="#B7C2CB", outline="#8192A0", width=1.2)
                canvas.create_oval(cx - 10, cy - 13, cx + 10, cy - 5, fill="#CFD6DC", outline="#8192A0", width=1.0)
            elif kind == "merge":
                canvas.create_arc(cx - 24, cy - 18, cx + 24, cy + 18, start=15, extent=160, style="arc", outline="#60C5D8", width=5)
                canvas.create_oval(cx - 13, cy - 9, cx + 13, cy + 9, fill="#F0F0F0", outline="#9A9A9A", width=1)
                canvas.create_line(cx - 6, cy - 2, cx + 8, cy - 7, fill="#D9534F", width=2)
                canvas.create_line(cx - 2, cy + 5, cx + 12, cy + 1, fill="#D9534F", width=2)
            else:
                draw_boolean_icon(cx, cy)

        def draw_node(
            x0: float,
            y0: float,
            x1: float,
            y1: float,
            *,
            title: str,
            name: str,
            sublabel: str | None = None,
            icon: str = "boolean",
            title_dx: float = 14,
            title_dy: float = -12,
            current: bool = False,
            selected: bool = False,
            halo: bool = False,
        ) -> dict[str, tuple[float, float]]:
            draw_node_body(x0, y0, x1, y1, current=current, selected=selected, halo=halo)
            draw_simple_icon((x0 + x1) / 2, (y0 + y1) / 2, icon)

            top_left = (x0 + 28, y0 - 8)
            top_right = (x0 + 68, y0 - 8)
            bottom = ((x0 + x1) / 2, y1 + 8)
            draw_port(*top_left)
            draw_port(*top_right)
            draw_port(*bottom)

            text_x = x1 + title_dx
            text_y = y0 + title_dy
            if title:
                canvas.create_text(text_x, text_y, anchor="nw", text=title, fill=rgb_to_hex(node_type_text), font=("Segoe UI", 10))
            canvas.create_text(text_x, text_y + 26, anchor="nw", text=name, fill=rgb_to_hex(node_text), font=("Segoe UI", 12))
            if sublabel:
                canvas.create_text(text_x, y1 + 8, anchor="nw", text=sublabel, fill=rgb_to_hex(connector_label), font=("Segoe UI", 9))

            return {"top_left": top_left, "top_right": top_right, "bottom": bottom, "box": (x0, y0, x1, y1)}

        group = draw_node(24, 62, 132, 102, title="Group Create", name="top_face1", sublabel="Top", icon="group")
        blast = draw_node(24, 142, 132, 182, title="", name="blast2", sublabel="Top", icon="blast", title_dx=14, title_dy=0)
        extrude = draw_node(412, 102, 520, 142, title="PolyExtrude", name="extrude_base", icon="extrude")
        tube = draw_node(640, 102, 748, 142, title="", name="tube1", icon="tube", title_dx=12, title_dy=8)
        boolean1 = draw_node(532, 226, 640, 266, title="", name="boolean1", icon="boolean", title_dx=12, title_dy=8)
        boolean2 = draw_node(240, 248, 348, 288, title="", name="boolean2", icon="boolean", title_dx=12, title_dy=8, current=True, selected=True)
        merge1 = draw_node(446, 308, 554, 348, title="", name="merge1", icon="merge", title_dx=12, title_dy=12, selected=True, halo=True)

        canvas.create_line(group["bottom"][0], group["bottom"][1], 78, 126, blast["top_left"][0], blast["top_left"][1], fill=rgb_to_hex(wire), width=1.5, smooth=True)
        canvas.create_line(extrude["bottom"][0], extrude["bottom"][1], 544, 188, 562, 206, boolean1["top_left"][0], boolean1["top_left"][1], fill=rgb_to_hex(wire), width=1.6, smooth=True)
        canvas.create_line(tube["bottom"][0], tube["bottom"][1], 704, 176, 676, 204, boolean1["top_right"][0], boolean1["top_right"][1], fill=rgb_to_hex(wire), width=1.6, smooth=True)
        canvas.create_line(boolean1["bottom"][0], boolean1["bottom"][1], 640, 304, 596, 328, merge1["top_left"][0], merge1["top_left"][1], fill=rgb_to_hex(wire), width=1.6, smooth=True)

        canvas.create_line(blast["bottom"][0], blast["bottom"][1], 146, 212, 214, 234, boolean2["top_left"][0], boolean2["top_left"][1], fill=rgb_to_hex(wire_node_selection), width=1.8, smooth=True)
        canvas.create_line(boolean2["bottom"][0], boolean2["bottom"][1], 356, 314, 418, 330, merge1["top_right"][0], merge1["top_right"][1], fill=rgb_to_hex(wire_node_selection), width=1.8, smooth=True)

        start_x, start_y = boolean1["bottom"]
        end_x, end_y = boolean2["top_right"]
        canvas.create_line(start_x, start_y, 618, 272, 452, 238, 362, 240, end_x, end_y, fill=rgb_to_hex(wire_selection), width=2.2, smooth=True)
        canvas.create_polygon(574, 236, 600, 226, 596, 248, fill=rgb_to_hex(wire_selection), outline="")

        canvas.create_text(500, 338, anchor="nw", text="Selected / adjacent", fill=rgb_to_hex(wire_selection), font=("Segoe UI", 9))
        canvas.create_line(616, 345, 720, 345, fill=rgb_to_hex(wire_selection), width=2.2)
        canvas.create_text(500, 358, anchor="nw", text="Normal wire", fill=rgb_to_hex(wire), font=("Segoe UI", 9))
        canvas.create_line(584, 365, 662, 365, fill=rgb_to_hex(wire), width=1.8)

        canvas.create_text(
            22,
            height - 24,
            anchor="sw",
            text="Graph preview shows normal wire color, selected / adjacent wire color, and selected node outline together.",
            fill=rgb_to_hex(param_text),
            font=("Segoe UI", 9),
        )


def guess_default_path() -> Path | None:
    candidates = sorted(path for path in Path.cwd().glob("*.hcs") if path.is_file())
    if len(candidates) == 1:
        return candidates[0]
    return None


def parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Edit Houdini .hcs theme files with a simple UI preview.")
    parser.add_argument("theme", nargs="?", help="Path to a .hcs file")
    return parser.parse_args(list(argv))


def main(argv: Iterable[str]) -> int:
    args = parse_args(argv)
    path = Path(args.theme).expanduser() if args.theme else guess_default_path()
    root = tk.Tk()
    HCSThemeEditorApp(root, path)
    root.mainloop()
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
