"""Core parsing, filesystem, and color utilities for the Houdini theme editor."""

from __future__ import annotations

import colorsys
import os
import re
from dataclasses import dataclass
from pathlib import Path


LINE_RE = re.compile(
    r"^(?P<indent>\s*)(?P<key>[A-Za-z0-9_]+)\s*:\s*(?P<value>.*?)(?P<comment>\s*//.*)?$"
)
DEFAULT_NEW_THEME_NAME = "CustomTheme"


def build_overlay_template_lines(scheme_name: str) -> list[str]:
    name = scheme_name.strip() or DEFAULT_NEW_THEME_NAME
    return [
        "// Generated by Houdini Theme Editor.",
        "// This file contains only user-authored overrides.",
        "// It references Houdini's local dark theme and does not bundle SideFX files.",
        '#include "$HFS/houdini/config/UIDark.hcs"',
        f"Scheme: {name}",
        "",
    ]


def clamp01(value: float) -> float:
    return max(0.0, min(1.0, value))


def rgb_to_hex(rgb: tuple[float, float, float]) -> str:
    r, g, b = (round(clamp01(channel) * 255) for channel in rgb)
    return f"#{r:02X}{g:02X}{b:02X}"


def hex_to_rgb(value: str) -> tuple[float, float, float]:
    text = value.strip().lstrip("#")
    if len(text) == 6:
        return tuple(int(text[index:index + 2], 16) / 255.0 for index in (0, 2, 4))  # type: ignore[return-value]
    raise ValueError(f"Unsupported hex color: {value}")


def format_rgb(rgb: tuple[float, float, float]) -> str:
    return " ".join(f"{clamp01(channel):.3f}".rstrip("0").rstrip(".") or "0" for channel in rgb)


def parse_float_triplet(value: str) -> tuple[float, float, float] | None:
    parts = value.strip().split()
    if len(parts) != 3:
        return None
    try:
        return tuple(clamp01(float(part)) for part in parts)  # type: ignore[return-value]
    except ValueError:
        return None


def parse_hsv(value: str) -> tuple[float, float, float] | None:
    parts = value.strip().split()
    if len(parts) != 4 or parts[0].upper() != "HSV":
        return None
    try:
        hue = float(parts[1]) / 360.0
        sat = clamp01(float(parts[2]))
        val = clamp01(float(parts[3]))
    except ValueError:
        return None
    return colorsys.hsv_to_rgb(hue, sat, val)


def parse_grey(value: str) -> tuple[float, float, float] | None:
    match = re.fullmatch(r"GREY\(([^)]+)\)", value.strip(), re.IGNORECASE)
    if not match:
        return None
    try:
        grey = clamp01(float(match.group(1)))
    except ValueError:
        return None
    return (grey, grey, grey)


def parse_hex_variants(value: str) -> tuple[float, float, float] | None:
    text = value.strip()
    if not text.startswith("#"):
        return None
    compact = text[1:].replace(" ", "")
    if len(compact) != 6:
        return None
    return hex_to_rgb("#" + compact)


def parse_named_color(value: str) -> tuple[float, float, float] | None:
    text = value.strip().upper()
    if text == "BLACK":
        return (0.0, 0.0, 0.0)
    if text == "WHITE":
        return (1.0, 1.0, 1.0)
    return None


def parse_color_value(value: str) -> tuple[float, float, float] | None:
    for parser in (parse_float_triplet, parse_hsv, parse_grey, parse_hex_variants, parse_named_color):
        parsed = parser(value)
        if parsed is not None:
            return parsed
    return None


def adjust_hsv(
    rgb: tuple[float, float, float],
    *,
    hue_shift: float = 0.0,
    sat_scale: float = 1.0,
    val_scale: float = 1.0,
    sat_offset: float = 0.0,
    val_offset: float = 0.0,
) -> tuple[float, float, float]:
    hue, sat, val = colorsys.rgb_to_hsv(*rgb)
    hue = (hue + hue_shift) % 1.0
    sat = clamp01(sat * sat_scale + sat_offset)
    val = clamp01(val * val_scale + val_offset)
    return colorsys.hsv_to_rgb(hue, sat, val)


def build_channel_family_palette(base_rgb: tuple[float, float, float]) -> list[tuple[float, float, float]]:
    return [
        adjust_hsv(base_rgb, hue_shift=-0.035, sat_scale=0.72, val_scale=1.12, val_offset=0.03),
        adjust_hsv(base_rgb, hue_shift=0.025, sat_scale=0.96, val_scale=1.10, val_offset=0.02),
        adjust_hsv(base_rgb, hue_shift=0.0, sat_scale=1.00, val_scale=1.04),
        adjust_hsv(base_rgb, hue_shift=-0.02, sat_scale=0.92, val_scale=0.92),
        adjust_hsv(base_rgb, hue_shift=0.015, sat_scale=1.04, val_scale=0.66),
    ]


@dataclass
class HCSDocument:
    path: Path
    lines: list[str]

    @classmethod
    def load(cls, path: str | Path) -> "HCSDocument":
        target = Path(path)
        return cls(target, target.read_text(encoding="utf-8").splitlines())

    @classmethod
    def new_overlay(cls, scheme_name: str = DEFAULT_NEW_THEME_NAME, path: str | Path | None = None) -> "HCSDocument":
        name = scheme_name.strip() or DEFAULT_NEW_THEME_NAME
        target = Path(path) if path is not None else Path(f"{name}.hcs")
        return cls(target, build_overlay_template_lines(name))

    def __post_init__(self) -> None:
        self._reindex()

    def _reindex(self) -> None:
        self.key_to_index: dict[str, int] = {}
        self.key_to_meta: dict[str, tuple[str, str]] = {}
        self.key_to_value: dict[str, str] = {}
        for index, line in enumerate(self.lines):
            stripped = line.lstrip()
            if stripped.startswith("//") or stripped.startswith("#include"):
                continue
            match = LINE_RE.match(line)
            if not match:
                continue
            key = match.group("key")
            value = match.group("value").strip()
            comment = match.group("comment") or ""
            indent = match.group("indent") or ""
            self.key_to_index[key] = index
            self.key_to_meta[key] = (indent, comment)
            self.key_to_value[key] = value

    def get_color(self, key: str) -> tuple[float, float, float] | None:
        value = self.key_to_value.get(key)
        if value is None:
            return None
        return parse_color_value(value)

    def get_value(self, key: str) -> str | None:
        return self.key_to_value.get(key)

    def set_value(self, key: str, value: str) -> None:
        if key in self.key_to_index:
            indent, comment = self.key_to_meta.get(key, ("", ""))
            self.lines[self.key_to_index[key]] = f"{indent}{key}: {value}{comment}"
        else:
            self.lines.append(f"{key}: {value}")
        self._reindex()

    def set_color(self, key: str, rgb: tuple[float, float, float]) -> None:
        value = format_rgb(rgb)
        if key in self.key_to_index:
            indent, comment = self.key_to_meta.get(key, ("", ""))
            self.lines[self.key_to_index[key]] = f"{indent}{key}: {value}{comment}"
        else:
            self.lines.append(f"{key}: {value}")
        self._reindex()

    def save(self, path: str | Path | None = None) -> None:
        target = Path(path) if path is not None else self.path
        target.write_text(self.render_text(), encoding="utf-8")
        self.path = target

    def render_text(self) -> str:
        return "\n".join(self.lines) + "\n"

    def write_to(self, path: str | Path) -> Path:
        target = Path(path)
        target.write_text(self.render_text(), encoding="utf-8")
        return target

    def sync_scheme_name_to_path(self, path: str | Path) -> str:
        target = Path(path)
        scheme_name = target.stem.strip() or DEFAULT_NEW_THEME_NAME
        self.set_value("Scheme", scheme_name)
        return scheme_name


def parse_houdini_dir_version(name: str) -> tuple[int, ...]:
    lowered = name.lower()
    if not lowered.startswith("houdini"):
        return ()
    parts = re.findall(r"\d+", lowered[len("houdini"):])
    if not parts:
        return ()
    return tuple(int(part) for part in parts)


def find_houdini_config_dirs() -> list[Path]:
    candidates: list[Path] = []
    seen: set[str] = set()

    env_pref_dir = os.environ.get("HOUDINI_USER_PREF_DIR", "").strip()
    if env_pref_dir:
        config_dir = Path(env_pref_dir).expanduser() / "config"
        resolved = str(config_dir)
        if resolved not in seen:
            candidates.append(config_dir)
            seen.add(resolved)

    documents_dir = Path.home() / "Documents"
    if documents_dir.exists():
        for child in documents_dir.iterdir():
            if not child.is_dir():
                continue
            if not child.name.lower().startswith("houdini"):
                continue
            config_dir = child / "config"
            resolved = str(config_dir)
            if resolved in seen:
                continue
            candidates.append(config_dir)
            seen.add(resolved)

    return sorted(
        candidates,
        key=lambda path: (
            parse_houdini_dir_version(path.parent.name),
            path.parent.stat().st_mtime if path.parent.exists() else 0,
        ),
        reverse=True,
    )
